---
driver:
  name: docker
  use_sudo: false
  privileged: true
  reset_command: "exit 0"

provisioner:
  name: chef_zero
  product_name: chef
  product_version: "14"
  require_chef_omnibus: "14"
  data_bags_path: "test/data_bags"
  log_level: info

platforms:
  - name: <%= ENV["platform"] %>

verifier:
  name: inspec

suites:
  - name: Python3and2_pip19
    run_list:
      - recipe[poise-python]
    verifier:
      inspec_tests:
        - test/integration/base_python_tests
    attributes:
      poise-python:
        install_python3: true
        options:
          pip_version: 19
  - name: Python3and2_pip18
    run_list:
      - recipe[poise-python]
    verifier:
      inspec_tests:
        - test/integration/base_python_tests
    attributes:
      poise-python:
        install_python3: true
        options:
          pip_version: 18
